### ISSUE TITLE
Change the cache directory

### ISSUE THREAD

**Issue by LeiWang1999** [microsoft/antares#350]
I'm currently working in my docker container, now I wanna to commit the docker container to an image, but I found that the cache of the antares' database is located in home directory, any environment can change the default storage path?

<img width="399" alt="image" src="https://user-images.githubusercontent.com/34334180/170667310-931260d8-59ad-409f-99c7-99473a581fea.png">

**Comment by ghostplant** [comment]
Does soft link help on your requirement?

**Comment by LeiWang1999** [comment]
I think it can help, but any other solution? for example, just export `TORCH_HOME=/path/to/store/` then pytorch model will stored in a specified directory.

**Comment by ghostplant** [comment]
If you use antares's native docker support, there should be a soft link to {ANTARES_ROOT}/.libAntares，which allows the `codehub` data to be persistantly stored in host side.

Another choice is setting `export ANTARES_DRIVER_PATH=<your personal path>`, the codehub location inside docker container will be redirected to `{ANTARES_DRIVER_PATH}/codehub`.

**Comment by LeiWang1999** [comment]
Thanks @ghostplant
