### ISSUE TITLE
[Help Request] How can Antares IR support stride size > 1 's Slice operation?

### ISSUE THREAD

**Issue by LeiWang1999** [microsoft/antares#354]
Currently we got an issue when we use antares to tune a swin-transformer model, it has a slice operation which's steps can be larger that one.

But from the [AntaresIR.md](https://github.com/microsoft/antares/blob/v0.3.x/AntaresIR.md), we noticed that the ir can only support step size equal to 1, for a onnx model I made for antares slice operation test, which same to the onnx operation [documentation](https://github.com/onnx/onnx/blob/main/docs/Changelog.md#Slice-10) :

<img width="1024" alt="image" src="https://user-images.githubusercontent.com/34334180/178294382-278faa03-c10a-4ef1-a782-5a824894ef5d.png">

If the steps' data is [1, 1], we can simply get the antares ir code :

```bash
output0[N0, N1] = input0[N0 + 1, N1 + 0] where N0 in 1 , N1 in 3
```

but if the steps' data is [1, 2], it's hard to describe the compute logic :

```bash
output0[N0, N1] = input0[N0 + 1, N1 + 0] where N0 in 1 , N1 in {0, 2}
```

the N1 should jump over the index 2, but I don't find the way to come up with this idea.

So please any suggestion for this case?

**Comment by LeiWang1999** [comment]
Please CC @ghostplant , Thanks

**Comment by ghostplant** [comment]
Do you mean `output0[N0, N1] = input0[N0 + 1, N1 * {step} + {start}] where N0 in 1 , N1 in { ceil((end - start) / step) }`

**Comment by LeiWang1999** [comment]
LGTM, Thanks a lot!
@ghostplant
