### ISSUE TITLE
Can antares assign specified gpus for evaluation?

### ISSUE THREAD

**Issue by LeiWang1999** [microsoft/antares#358]
I have four gpus in my environment, each time I evaluated cuda backend, all the four gpus will run evaluator program, but I just wanna antare uses no more than two of them because I also need another gpus to profile other programs.

so can antares assign specified gpus for evaluation, actually I tried setting `CUDA_VISIBLE_DEVICES` but it didn't work, as I expected...

**Comment by ghostplant** [comment]
`DEVICE_ID=3 <.. other configs ..> antares`
