### ISSUE TITLE
Fail to compile, when I use "AMDGFX=gfx1031 BACKEND=c-rocm_win64 antares"

### ISSUE THREAD

**Issue by Looong01** [microsoft/antares#365]
Hey, there are my problems:
![image](https://user-images.githubusercontent.com/69568351/210217500-cc5a4bfb-7239-4a73-875c-e2dca277b622.png)

And when I input this:
![image](https://user-images.githubusercontent.com/69568351/210217738-67b3d064-031e-46ea-838a-fc0426a13c5b.png)
It returns this:
![image](https://user-images.githubusercontent.com/69568351/210217789-76d5f738-18e0-419c-9e98-fb636b1bb46e.png)

Andinstalled, automatic this things:
rocm-clang-ocl/focal,now 0.5.0.50401-84~20.04 amd64 [installed,automatic]
rocm-cmake/focal,now 0.8.0.50401-84~20.04 amd64 [installed,automatic]
rocm-core/focal,now 5.4.1.50401-84~20.04 amd64 [installed,automatic]
rocm-dbgapi/focal,now 0.68.0.50401-84~20.04 amd64 [installed,automatic]
rocm-debug-agent/focal,now 2.0.3.50401-84~20.04 amd64 [installed,automatic]
rocm-dev/focal,now 5.4.1.50401-84~20.04 amd64 [installed]
rocm-device-libs/focal,now 1.0.0.50401-84~20.04 amd64 [installed,automatic]
rocm-dkms/focal,now 5.4.1.50401-84~20.04 amd64 [installed]
rocm-gdb/focal,now 12.1.50401-84~20.04 amd64 [installed,automatic]
rocm-llvm/focal,now 15.0.0.22465.50401-84~20.04 amd64 [installed,automatic]
rocm-ocl-icd/focal,now 2.0.0.50401-84~20.04 amd64 [installed,automatic]
rocm-opencl-dev/focal,now 2.0.0.50401-84~20.04 amd64 [installed]
rocm-opencl/focal,now 2.0.0.50401-84~20.04 amd64 [installed,automatic]
rocm-smi-lib/focal,now 5.0.0.50401-84~20.04 amd64 [installed,automatic]
rocm-utils/focal,now 5.4.1.50401-84~20.04 amd64 [installed,automatic]
rocminfo/focal,now 1.0.0.50401-84~20.04 amd64 [installed, automatic]

I succeed to use this:
![image](https://user-images.githubusercontent.com/69568351/210217639-4aee814e-2b6b-4494-b0b1-b0dfe25315a8.png)

**Comment by Looong01** [comment]
Ok, I use this:
![image](https://user-images.githubusercontent.com/69568351/210221383-e89ee8e9-685f-4fb4-9465-2f8dbf7f85f9.png)

And then this:
![image](https://user-images.githubusercontent.com/69568351/210221450-213cfaa7-0361-43df-ba79-7eca0ac078a8.png)
It returns this:
![image](https://user-images.githubusercontent.com/69568351/210221507-b4d407c1-063f-4d9c-9d6f-2987c70d43b7.png)

**Comment by Looong01** [comment]
作者你好，如果你愿意用中文的话，还是中文我理解得比较好😂

**Comment by Looong01** [comment]
Actually, I can quote "cmath" to compile things.
![image](https://user-images.githubusercontent.com/69568351/210224300-adc25a0e-9c89-4f1a-a983-e715f5d4eb78.png)
![image](https://user-images.githubusercontent.com/69568351/210224326-d5eff484-34d1-490e-8a5b-74b0b4c67682.png)

**Comment by ghostplant** [comment]
Have you installed CXX development dependencies in WSL? e.g.
```sh
sudo apt install g++
sudo apt install g++-mingw-w64-x86-64
```

**Comment by Looong01** [comment]
> Have you installed CXX development dependencies in WSL? e.g.
> 
> ```shell
> sudo apt install g++
> sudo apt install g++-mingw-w64-x86-64
> ```

Yes.

**Comment by ghostplant** [comment]
Is this command successful in WSL?

```
echo -e '#include <cmath>\nint main() {}' > main.cpp && x86_64-w64-mingw32-g++ main.cpp
```

**Comment by Looong01** [comment]
> Is this command successful in WSL?
> 
> ```
> echo -e '#include <cmath>\nint main() {}' > main.cpp && x86_64-w64-mingw32-g++ main.cpp
> ```

It returned nothing, and generate an "a.exe" file.
![image](https://user-images.githubusercontent.com/69568351/210568018-23b240fa-1bb4-404d-8b9b-900657e9c3fe.png)

**Comment by ghostplant** [comment]
This is not an Antares environmental issue, but ROCm issue for HIP versions >= 5.3.0. Please use ROCm < 5.3.0 or follows: https://github.com/RadeonOpenCompute/ROCm/issues/1843

**Comment by Looong01** [comment]
> This is not an Antares environmental issue, but ROCm issue for HIP versions >= 5.3.0. Please use ROCm < 5.3.0 or follows: [RadeonOpenCompute/ROCm#1843](https://github.com/RadeonOpenCompute/ROCm/issues/1843)

Thank you!
Now I have succeeded to install these and to run "AMDGFX=gfx1031 BACKEND=c-rocm_win64 Antares".

![image](https://user-images.githubusercontent.com/69568351/211019269-d7a47b9e-1e75-4682-bbcb-d8491c6269af.png)

**Does this mean I have successfully configured related environment for PyTorch for ROCm?** 

**Now, how can I test if I have done this correctly?
Command "rocminfo" still cannot work.**

And I used "pip install" to install a ROCm version of PyTorch in anaconda virtual environment. And I encountered errors when I try to use "torch.cuda.is_available()". It returned:

/home/dragons/anaconda3/envs/PyTorch/lib/python3.9/site-packages/torch/cuda/__init__.py:88: UserWarning: HIP initialization: Unexpected error from hipGetDeviceCount(). Did you run some cuda functions before calling NumHipDevices() that might have already set an error? Error 101: hipErrorInvalidDevice (Triggered internally at ../c10/hip/HIPFunctions.cpp:110.)
  return torch._C._cuda_getDeviceCount() > 0
