### ISSUE TITLE
Is this project based on AI? What is the goal of this project?

### ISSUE THREAD

**Issue by yhyu13** [microsoft/antares#372]
Hi,

Just come across this project, I tried to run 

```
# Search an efficient CUDA code for MatMul, using 2000 steps for trial:
BACKEND=c-cuda STEP=2000 COMPUTE_V1='- S = 512; einstein_v2(input_dict={"input0": {"dtype": "float32", "shape": [S, S]}, "input1": {"dtype": "float32", "shape": [S, S]}}, exprss="output0[N, M] +=! input0[N, K] * input1[K, M]")' antares
```

And it seems to generate and evaluate code on my GPU for 2000 runs.

I am not sure if this project involve LLM generating code and reinforcement learning in code optimization. Maybe a stupid question, could some explain breifly what is the end game goal of this project?
```[tasklist]
### Tasks
```

**Comment by ghostplant** [comment]
Hi, does the current README.md answer your questions?

**Comment by yhyu13** [comment]
It's pretty much like what mojo's ML IR does? And this project mainly focus creating an adpater that enhance pytorch performance on specific compute backend?

**Comment by ghostplant** [comment]
Enhancing pytorch performance is one of the jobs. It also targets devices not supported by ML IR.
